### PR TITLE
"For" tag optimization

### LINKED ISSUE #93: Variable bug inside 2 loops
Hi,

There is a problem with variables inside 2 loops. I don't understand what is happening, but the variable get messed up.

Example:
http://pastebin.com/XADwCV3j

The same in JS:
http://pastebin.com/wXPjhLy7

### PR DESCRIPTION
**Pull request by evgenius**
Fixes #93, #144, #191, #210

### CODE REVIEW

**Comment by evgenius** [comment]
@jmealo Since you're active: mind looking into this?

**Comment by jmealo** [comment]
@evgenius I don't think that I have time right now, but this definitely needs to get addressed.

**Comment by evgenius** [comment]
@jmealo I might be not clear. It's a PR, not an issue to resolve.
But if you realize it's a PR and just don't have time to review it, no problem :)

**Comment by evgenius** [comment]
Hi @justjohn ,

Could you please review this PR?
I'm too excited about using prototypes here so I may be missing something.

**Comment by justjohn** [comment]
This looks solid. Using the prototype to extend the context seems like exactly the right approach, since it should work down multiple levels correctly. It may be worth defining a `Twig.Context` model more globally in the project, so this can be reused elsewhere.

**Comment by evgenius** [comment]
@justjohn Thanks for reviewing it.
Defining Context makes sense only in that function scope. Otherwise we won't be able to change its prototype.
The idea is that you define a new Context function in the loop, set old context as its prototype (i.e. context parent) and instantiate a new context variable. If we go deeper (to a nested loop), a new function Context is declared and now the context above become a prototype of this new function.
So we can't define a global Context function.

**Comment by justjohn** [comment]
This is more then should happen in this PR, but what I had in mind when I suggested a global Twig.Context object was mostly just encapsulating exactly what you wrote in a more reusable place. Something roughly like this:

```js
// Context object definition
Twig.Context = function(context) {
    // copy everything from context to this
    if (context) for (key in context) {
        if (context.hasOwnProperty(key)) {
            // prevent obscuring methods on base prototype
            if (!this[key]) this[key] = context[key]
        }
    }
}
Twig.Context.prototype = {
    _createChild: function() {
        function Context() {}
        Context.prototype = this;
        return new Context();
    }
}
```

Then to create the base context for the template you use:

```js
var context = new Twig.Context(user_provided_context);
```

And anytime you need to generate a child context in a tag, you can do:

```js
parse: function (token, context, continue_chain) {
    ...
    loop = function(key, value) {
        var inner_context = context._createChild();
    ...
}
```

Since `Twig.Context` lives at the top of the prototype chain for all contexts, `_createChild` is always available. This is a more reusable way of generating child contexts, since it may be necessary in more then just the `for` tag.

**Comment by evgenius** [comment]
@justjohn I'm lost for words... Looks great :)
Let's merge this one and then implement your idea. Do you want to do it yourself or want me to create a commit? I'm not going to put my name as an author of that commit as it looks too awesome :)

**Comment by justjohn** [comment]
I'll implement it and commit it this evening, since I've already written most of it :smiley:

**Comment by evgenius** [comment]
@justjohn :
Isn't it more compact:
```js
Twig.Context = function (context) {
    function Context() {}
    Context.prototype = context;
    return new Context();
}

var context = Twig.Context(user_provided_context);
var inner_context = Twig.Context(context);
```

Am I missing something?

**Comment by evgenius** [comment]
And we wouldn't need to have a service method `_createChild()` in the context object.

**Comment by justjohn** [comment]
It is more compact, but it loses the benefits of being an object you can add service methods to. I see that as a benefit since it means they follow the context around. For example, if you're extending twig with your own custom for loop, you don't need access to the twig internals to create a child context.

**Comment by justjohn** [comment]
I've added a `Twig.Context` object in ad55f6b59ab585d0f698bb06ea2fa83f156c75ed, It's pretty close to what's described here. I've also added a `_merge` function for folding changes from a child context back in, so all the logic now lives in one place.

**Comment by evgenius** [comment]
@justjohn Great job, thanks.
Do you think it's time to release 0.8.0?

**Comment by justjohn** [comment]
Yes, I think it is. Unless you have anything else you specifically want to get in, I'll push 0.8.0 up this evening.

**Comment by evgenius** [comment]
Would be great, thanks!

**Comment by createvibe** [comment]
Thank you guys so much for working on this!  It was much needed.  Can't wait for the release.

**Pull request merged**
