### PR TITLE
Refactor Path resolution out to its own module

### PR DESCRIPTION
**Pull request by dave-irvine**
I'm getting ready to make some additions to namespace handling, but I wanted to get some tests in place first.

I know that usually we tend to test only the output of a `render()` command (and in fact this made these changes quite tricky to test!), but in this case I think the actual internal functions need testing to make sure that further changes don't break how they work.

I've had to include additional testing frameworks to be able to stub functions and test them using the BDD language in use elsewhere, but I've tried to ensure they don't conflict with any other tests.

Ideally I'd like to not have the module in Twig's exports, but I can't find a reliable way to access the functions in the module without doing this, short of rewriting all of Twig's modules to be actual modules that are then `require()`'d into the main Twig module.

Happy to discuss and make changes, want to get this out the way before I make any further changes to namespacing support.

### CODE REVIEW

**Comment by dave-irvine** [comment]
Well, silly me, looks like the changes I was about to make have actually been made in another pull request already.

https://github.com/justjohn/twig.js/pull/320

Maybe Path resolution should still be factored out to add these tests though?

**Comment by dave-irvine** [comment]
https://github.com/justjohn/twig.js/pull/321 is another pull request that wants to modify path resolution.

**Comment by dave-irvine** [comment]
Any thoughts on this @plepe?

**Comment by plepe** [comment]
I think your pull request is much more complete than #320. On the other hand, I don't see that you enabled namespaces with '@'?

Do you mind if I merge #320?

**Comment by dave-irvine** [comment]
Mine is a sort of precursor to #320. By all means you can merge that but then I'll need to rebase mine, alternatively you can merge mine and the very next thing I will do is implement #320s change because that's the feature I want :)

**Comment by plepe** [comment]
@dave-irvine I don't mind. What do you prefer?

**Comment by dave-irvine** [comment]
Go ahead and merge this and I'll all the work from #320 before the end of the day. Please leave #320 open for now

**Comment by plepe** [comment]
There are some conflicts - can you see if you can resolve them? Thanks!

**Comment by dave-irvine** [comment]
@plepe Done

**Pull request merged**
