### PR TITLE
Fix "is defined" test

### PR DESCRIPTION
**Pull request by plepe**
see #160

### CODE REVIEW

**Comment by plepe** [comment]
Anyone (e.g. @createvibe because you are quite active recently) wants to review this pull request? See #160 for explanation.

**Comment by createvibe** [comment]
@plepe I found an issue with nested objects.

```
var context = {
    key: {
        nested: {
            data: "nested data"
        }
    }
};

twig({data: '{{ key.nested.fail is defined }}'}).render(context).should.equal( "false" );
```

The above is returning "true" instead of "false" and causes the test to fail.

It is returning true on "key.nested.anything" because key.nested is defined.  I don't think it's looking further than the first period.

Is this expected?

**Comment by createvibe** [comment]
shoot I'm sorry @plepe, I spoke too soon.  For some reason make didn't want to regenerate the twig files.  it all works good.  CR passes.  :)

**Comment by plepe** [comment]
Awesome :-) Then I'll merge.

**Pull request merged**
