### PR TITLE
Implement iterable test

### PR DESCRIPTION
**Pull request by jmealo**
This implements the ``iterable`` test.

In addition, it checks for an ES6 iterable function on passed in values.

### CODE REVIEW

**Comment by enzolutions** [comment]
I want to fix this patch but I don't know how to upload a fix of someone else PR, any idea?

**Comment by jmealo** [comment]
@enzolutions You can do a pull request against my iterable branch. What's wrong with it? All of the Travis CI builds fail.

**Comment by enzolutions** [comment]
Git hub report merge conflicts is just re-roll the patch with latest version, if you can do will be better.

This operator is really necessary :P

**Comment by jmealo** [comment]
Ah, I didn't even see the merge conflicts shown under the Travis error. Let me try to rebase.

**Comment by jmealo** [comment]
@enzolutions It merges cleanly now. Give that a try.

**Comment by enzolutions** [comment]
Cool, well I just want to fix in order the maintainer can consider to apply in next release

**Comment by jmealo** [comment]
@evgenius It appears you are correct. I think those documents have been updated since I implemented this. It appears that the property is ``Symbol.iterator``... Since it's experimental, it'd probably be best to remove it for now. Don't you think?

**Comment by evgenius** [comment]
Yeah, that's what I thought. I think we can add support of this feature later if needed.
Could you please also recommit and force-update your branch to include only src/twig.tests.js and
test/test.tests.js? Thank you!

**Comment by jmealo** [comment]
@evgenius done.

**Comment by evgenius** [comment]
looks good to me, thanks.

**Pull request merged**
