### PR TITLE
Ignore quotes between {% raw %} and {% endraw %}

### LINKED ISSUE #283: Verbatim tag doesn't ignore contained strings
The following twig

```twig
{% verbatim %}
"
{% endverbatim %}
```

produces `Unclosed string in template`. On master right now it says it's at `twig.js:341`.

### PR DESCRIPTION
**Pull request by stremglav**
Fixes #283

### CODE REVIEW

**Comment by evgenius** [comment]
Thanks @stremglav .

**Comment by tremby** [comment]
Does this cover "verbatim" too? It's not clear just from the diff.

**Comment by evgenius** [comment]
@tremby Yeah, these tags are aliases.

**Comment by tremby** [comment]
Great, thanks.

**Pull request merged**
