### PR TITLE
Combined pull request

### PR DESCRIPTION
**Pull request by plepe**
I've noticed that there were quite some pull requests in the previous months, but apparently the project is currently rather unmaintained. I decided to pick up some of the pull requests and create a combined pull request. I'm still in the process of doing so, but this branch already contains the following pull requests:
- [x] #278 Improve 'sort' filter
- [x] #279 Improve 'json_encode' filter
- [x] #276 Filter 'date': update to current phpjs strtotime() function
- [ ] #267 Default filter now takes no params
- [x] #266 Add support for whitespace control modifier
- [x] #259 [Fix] Dont validate template id without cache
- [x] #251 (resp. #195) Support to twig namespaces (rebased)
- [x] #240 Support xmlhttp.status==0 when using cordova
- [x] #233 Validate ID only when caching is enabled
- [x] #186  Allow int 0 as a key in objects (modified pull request by @evgenius )
- [x] #264 Improving sub template file loading
- [x] #284 Add support for expressions as object keys 

Marked are all pull requests which are already merged to master.

Created a changelog file: https://github.com/plepe/twig.js/blob/merge/CHANGELOG.md

Still missing:
* #270 Support `undefined` and `null` values for the `in` operator [tests missing]
* #268 Twig.parse did not always return a string [tests failing]
* #242 Implemented tests of array casting [only tests, no fix]
* #236 Allow expressions as keys in an object [tests failing]
* #252 Normalize provided template path [not working in browsers]

### CODE REVIEW

**Comment by plepe** [comment]
forced push, as I removed pull request #252.

**Comment by plepe** [comment]
@justjohn @evgenius shall I start to merge these pull requests to master?

I'd do it individually and cancel out the merge branch, as one of the features has already been merged and it might be somehow cleaner.

Are there any rules when a pull request may be merged to master (other than the obvious constraint that all tests are passing)?

Btw, do you mind if I create some labels, e.g. for 'feature', 'bugfix', 'feature request', ...

**Comment by justjohn** [comment]
Nothing special. The only thing to make sure is the version of twig.js and twig.min.js are current in the repository by running `make` and `make test` after merging a bunch of pull requests. A group as large as this warrants a new point version release ([some instructions](https://github.com/justjohn/twig.js/blob/master/docs/release%20checklist.md)). So I'd push a tag for 0.8.5. I'll need to get your npmjs.org username from you, so you can add it as a collaborator.

@evgenius: I don't think I ever got a npm username from you - if you give it to me I'll add it as a collaborator as well.

**Comment by plepe** [comment]
Sure, I'd planned to create a release after merging.

My npm username is 'plepe' as well (I just created the account there).

**Comment by evgenius** [comment]
@plepe When you commit, can you include only source files into the commits? Then we'll have less conflicts when merging PRs. We build a final file when releasing a new version.
As of Travis CI, it builds everything automatically when testing so it doesn't needs compiled files to be up-to-date.

**Comment by evgenius** [comment]
@justjohn It's `evgenius`, I've just signed up.

**Comment by evgenius** [comment]
@plepe As of the labels, they're totally fine, I think.

**Comment by plepe** [comment]
About the commits: Will do in the future ...

**Comment by plepe** [comment]
@evgenius About source code commits: I included a section about this on the [Contributing wiki page](https://github.com/justjohn/twig.js/wiki/Contributing) and a note in the [installation instructions](https://github.com/justjohn/twig.js/wiki#download) (that the build files may not be up-to-date).

**Comment by evgenius** [comment]
@plepe: great, thanks!
Maybe it's worth adding a tag "latest" and modify the git command to `git clone -b latest git://github.com/justjohn/twig.js.git` to guarantee that a user gets a released version?

**Comment by plepe** [comment]
Hmm, I don't know. I think if somebody clones the repository, they might want a development version anyway? We can add a note how to get the last released version via git though (then the tag would make sense).

**Comment by justjohn** [comment]
My preference is to keep master as the dev branch, I think that's pretty common practice and makes contributing though github easier. If someone wants a release version, the git tags are easy enough to download through github. My guess is that a lot (most?) people who care about using release versions will be using a package manager like npm or bower, which uses the release versions by default.

I like the point about adding a note on getting release versions though, so I'm going to link https://github.com/justjohn/twig.js/releases from the README.

**Comment by plepe** [comment]
As I just made the 0.8.5 release (which was hopefully fine for everybody and I made everything correct), I'm going to close this pull request now.

**Comment by justjohn** [comment]
Looks good, thanks for putting the release together!

**Comment by plepe** [comment]
My pleasure :-)

**Pull request closed without merging**
