### PR TITLE
Fix Twig.renderFile (issue #302)

### PR DESCRIPTION
**Pull request by createvibe**
Defensive code and clean up in Twig.exports.renderFile in an attempt to fix issue #302

### CODE REVIEW

**Comment by plepe** [comment]
Could you please include in the commit messages what the commit is doing?

**Comment by createvibe** [comment]
Sorry about that, @plepe, I will be more descriptive in the future.  Would you like me to make a new PR or just amend the commit message?

**Comment by plepe** [comment]
Just amend them - that's what I also do ...

PS: then you can also get rid of the "oops, thought I removed this..." ;-)

**Comment by plepe** [comment]
Btw, don't need to write the issue number in the header of the commit message. You could include "fixes #302" in the commit body to indicate that this issue is resolved (which will be parsed by Github and it will close #302 as soon as the pull request gets merged to master, see [here](https://help.github.com/articles/closing-issues-via-commit-messages/)).

I'd also rather set meaningful pull request titles.

**Comment by plepe** [comment]
So, what's keeping you from updating the commit messages? It's the only thing blocking the 0.8.8 release, as the other pull request is finished (haven't merged yet).

**Comment by createvibe** [comment]
@plepe sorry for the delay

**Comment by plepe** [comment]
In the second commit you are just removing code you added in the first commit. Wouldn't it be more sensible to merge these commits? (If I remember correctly you stated "oops, thought I removed this..." in the second commit as comment - see my message above)

**Comment by createvibe** [comment]
done

**Comment by plepe** [comment]
Thanks!

**Pull request merged**
